// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfBc0H-Qjxb1_BzR-lQKS2SN0x1k5Pr8s',
    appId: '1:777373976161:web:1e6bc5c41329e15fd9cc20',
    messagingSenderId: '777373976161',
    projectId: 'profile-app-eeb4b',
    authDomain: 'profile-app-eeb4b.firebaseapp.com',
    storageBucket: 'profile-app-eeb4b.firebasestorage.app',
    measurementId: 'G-NNXJMBSJ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlr1EoOsbJmxZLjiHEgetI_d9_u6lY1C4',
    appId: '1:777373976161:android:ee64d3c5894203dfd9cc20',
    messagingSenderId: '777373976161',
    projectId: 'profile-app-eeb4b',
    storageBucket: 'profile-app-eeb4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4UFkxiCTVijHXQXyiPdK7DX1TUQOHrWQ',
    appId: '1:777373976161:ios:9504b4ccdf53f30cd9cc20',
    messagingSenderId: '777373976161',
    projectId: 'profile-app-eeb4b',
    storageBucket: 'profile-app-eeb4b.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4UFkxiCTVijHXQXyiPdK7DX1TUQOHrWQ',
    appId: '1:777373976161:ios:9504b4ccdf53f30cd9cc20',
    messagingSenderId: '777373976161',
    projectId: 'profile-app-eeb4b',
    storageBucket: 'profile-app-eeb4b.firebasestorage.app',
    iosBundleId: 'com.example.messageBoard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfBc0H-Qjxb1_BzR-lQKS2SN0x1k5Pr8s',
    appId: '1:777373976161:web:4ee6ce73aacc48c1d9cc20',
    messagingSenderId: '777373976161',
    projectId: 'profile-app-eeb4b',
    authDomain: 'profile-app-eeb4b.firebaseapp.com',
    storageBucket: 'profile-app-eeb4b.firebasestorage.app',
    measurementId: 'G-FNJ4VEEJME',
  );
}
